title: 'POKI & THE LOCOS'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#32332C'
    - '#F1D037'
    - '#F15E22'
    - '#54BFC4'
    - '#A79026'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Poki & the Locos'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0
