name: 'Poki & the Locos'
favicon: null
layout_spectrum: 0.74685
typography_spectrum: 0.23804
title: CoverBand
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8f9ff'
    - '#00022c'
    - '#ffbdaf'
    - '#583c2e'
    - '#e13d5b'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
