name: 'Poki & the Locos'
favicon: null
layout_spectrum: 0.7539
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#616360'
    - '#fed1ba'
    - '#ea9f7f'
    - '#abaead'
  brandStrength: 1
  lightness: 1
  saturation: 0.5318890153430402
  rhythmicContrast: 0.75
purpose: []
