title: CoverBand
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 0.7580645
  brandColors:
    - '#FFFFFF'
    - '#171520'
    - '#5430CE'
    - '#FB7FAC'
    - '#6F916D'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Poki & the Locos'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 1
