name: 'Poki & the Locos'
favicon: null
layout_spectrum: 0.74685
typography_spectrum: 0.23804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00000c'
    - '#ffffff'
    - '#dd9679'
    - '#e33e8d'
    - '#697045'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
