name: 'Poki & the Locos'
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'POKI & THE LOCOS'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#171520'
    - '#5430CE'
    - '#FB7FAC'
    - '#6F916D'
  brandStrength: 0
  lightness: 0.7580645
  saturation: 0
  rhythmicContrast: 0
purpose: []
